name: Publish a Github release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]*"
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install "build" module
        run: python -m pip install build
      - name: Create wheel (and store its name in env.wheel)
        run: python -m build && echo "wheel=$(ls dist/*.whl)" >> $GITHUB_ENV
      - name: Install wheel with dev dependencies
        run: python -m pip install ${{ env.wheel }}[dev]
      - name: Test the installed wheel
        run: python -m pytest -vv .
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          generateReleaseNotes: "true"
          assets: |
            - path: dist/*
